title = "Sadness Monday"
baseURL = "https://sadnessmonday.com"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke", "hugo-shortcode-kofi"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  [params.kofi]
    username = "praetorblue"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[[menu.main]]
name = "Nomads"
url = "NomadsDocs/index.html"
weight = 50

[[menu.main]]
name = 'Contact'
url = '/pages/contact'
weight = 30
